# Generated by Django 4.2.4 on 2023-09-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_medicinelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
