# Generated by Django 4.2.5 on 2023-09-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_patienthistory_consultcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='attachments',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
