# Generated by Django 4.2.5 on 2023-09-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_patienthistory_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientsAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.CharField(max_length=50)),
                ('fileattachments', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='patienthistory',
            name='attachments',
        ),
    ]
