# Generated by Django 4.2.5 on 2023-09-24 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_patientsattachments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsattachments',
            name='patient_code',
        ),
        migrations.AddField(
            model_name='patientsattachments',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.patient'),
        ),
    ]
