# Generated by Django 4.2.5 on 2023-09-24 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_patientsattachments_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsattachments',
            name='patient_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.patient'),
        ),
    ]
