# Generated by Django 4.2.5 on 2023-09-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_patientsattachments_patient_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsattachments',
            name='patient_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
