# Generated by Django 4.2.5 on 2023-09-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_patientsattachments_patient_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsattachments',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
