# Generated by Django 4.2.5 on 2023-09-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_patienthistory_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistory',
            name='diagnosis',
            field=models.TextField(blank=True, default='*under observation', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='remarks',
            field=models.TextField(max_length=500),
        ),
    ]
