# Generated by Django 4.2.5 on 2023-09-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_patienthistory_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistory',
            name='remarks',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
