# Generated by Django 4.2.5 on 2023-10-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_patientsattachments_consultcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pwdID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='srID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
