# Generated by Django 4.2.5 on 2023-10-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_patient_nationality_patient_pwdid_patient_srid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='bp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
