# Generated by Django 4.2.5 on 2023-11-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_patienthistory_bodytemp_patienthistory_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='consultCounter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
