# Generated by Django 4.2.5 on 2023-12-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_prescription_medduration_prescription_medgenname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='evening',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='morning',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='noon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
