# Generated by Django 4.2.5 on 2023-12-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_rename_medunit_prescription_durationqty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosageduration',
            name='daysqty_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
