# Generated by Django 4.2.5 on 2023-12-13 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_medicinelist_medgenname_medicinelist_medname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinelist',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='medicinelist',
            name='medicine_name',
        ),
    ]
