# Generated by Django 4.2.5 on 2023-12-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_remove_medicinelist_dosage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
