# Generated by Django 4.2.5 on 2024-01-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_alter_patienthistory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistory',
            name='objectives',
            field=models.TextField(blank=True, default='*under observation', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='plans_recommendations',
            field=models.TextField(blank=True, default='*under observation', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='remarks',
            field=models.TextField(blank=True, default='*under observation', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patientsattachments',
            name='fileattachments',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
