# Generated by Django 4.2.5 on 2024-01-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_alter_patienthistory_objectives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsattachments',
            name='atype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
