# Generated by Django 4.2.5 on 2024-01-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_patientsattachments_atype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientsattachments',
            old_name='fileattachments',
            new_name='fileattachments_video',
        ),
        migrations.AddField(
            model_name='patientsattachments',
            name='fileattachments_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
