# Generated by Django 4.2.5 on 2024-01-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_rename_fileattachments_patientsattachments_fileattachments_video_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientsattachments',
            old_name='fileattachments_image',
            new_name='fileattachments',
        ),
        migrations.RemoveField(
            model_name='patientsattachments',
            name='fileattachments_video',
        ),
    ]
