# Generated by Django 4.2.5 on 2024-01-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_rename_fileattachments_image_patientsattachments_fileattachments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsattachments',
            name='fileattachments',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
