# Generated by Django 4.2.5 on 2024-01-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_alter_patientsattachments_fileattachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('userLog', models.CharField(blank=True, max_length=50, null=True)),
                ('logMessage', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
