# Generated by Django 4.2.5 on 2024-03-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_alter_systemlog_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('labresultdate', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_code', models.CharField(blank=True, max_length=50, null=True)),
                ('labname', models.CharField(blank=True, max_length=50, null=True)),
                ('labresult', models.CharField(blank=True, max_length=50, null=True)),
                ('labrange', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
